# Deployed commit: 50a1ebf

config-server:
  image:
    tag: latest

discovery-server:
  image:
    tag: latest

customers-service:
  enabled: true # <-- Add flag
  image:
    tag: latest

api-gateway:
  enabled: true # <-- Add flag
  image:
    tag: latest

vets-service:
  enabled: false # <-- Add flag
  image:
    tag: latest

visits-service:
  enabled: false # <-- Add flag
  image:
    tag: latest

admin-server:
  enabled: false # <-- Add flag
  image:
    tag: latest

genai-service:
  enabled: false # <-- Add flag
  image:
    tag: latest