# helm-charts/petclinic-umbrella/values.yaml

configServer:
  image:
    tag: latest

discoveryServer:
  image:
    tag: latest

customersService:
  enabled: true # <-- Add flag
  image:
    tag: latest

apiGateway:
  enabled: true # <-- Add flag
  image:
    tag: latest

vetsService:
  enabled: false # <-- Add flag
  image:
    tag: latest

visitsService:
  enabled: false # <-- Add flag
  image:
    tag: latest

adminServer:
  enabled: false # <-- Add flag
  image:
    tag: latest

genaiService:
  enabled: false # <-- Add flag
  image:
    tag: latest