admin-server:
  image:
    tag: v0.1.5
api-gateway:
  image:
    tag: v0.1.5
config-server:
  image:
    tag: v0.1.5
customers-service:
  image:
    tag: v0.1.5
discovery-server:
  image:
    tag: v0.1.5
genai-service:
  image:
    tag: v0.1.5
vets-service:
  image:
    tag: v0.1.5
visits-service:
  image:
    tag: v0.1.5
