config-server:
  image:
    tag: latest

discovery-server:
  image:
    tag: latest

customers-service:
  enabled: true
  image:
    tag: latest

api-gateway:
  enabled: true
  image:
    tag: latest

vets-service:
  enabled: true
  image:
    tag: latest

visits-service:
  enabled: true
  image:
    tag: latest

admin-server:
  enabled: false
  image:
    tag: latest

genai-service:
  enabled: false
  image:
    tag: latest