# helm-charts/petclinic-umbrella/charts/api-gateway/values.yaml

replicaCount: 1

image:
  # Use your Docker Hub username and the correct image name prefix
  repository: 22127422/spring-petclinic-api-gateway
  pullPolicy: IfNotPresent
  # tag - Default tag, overridden by Jenkins during deployment.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080     # API Gateway port

# API Gateway specific configuration - most routing comes from Config Server/Discovery

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 256Mi # Adjust as needed
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
# Ingress configuration for api-gateway
ingress:
  enabled: true # Default to disabled; we will enable it via Argo CD per environment
  # Optional: Specify ingress class if you have multiple or specific requirements
  # className: "nginx"
  hostname: api-gateway.local # Default hostname, will be overridden
  path: /
  pathType: Prefix # Or ImplementationSpecific depending on your controller
  # annotations: {} # Add any specific ingress annotations here if needed
  # tls: [] # Add TLS configuration here if needed later
  #  - secretName: my-tls-secret
  #    hosts:
  #      - api-gateway.local